[workspace]
resolver = "2"
members = [
    "crates/mtp-rs",
    "crates/mtp-rs-cli",
    "benchmarks/mtp-rs-vs-libmtp",
]

[workspace.package]
edition = "2021"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
repository = "https://github.com/vdavid/mtp-rs"
authors = ["David Veszelovszki <veszelovszki@gmail.com>"]

[workspace.lints.clippy]
# Inherit clippy.toml at the workspace root.
